image:
  name: hashicorp/terraform:1.16
  entrypoint:
  - '/usr/bin/env'
  - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables:
    AWS_ACCESS_KEY_ID:     ${MY_AWS_ACCESS_KEY}
    AWS_SECRET_ACCESS_KEY: ${MY_AWS_SECRET_KEY}
    AWS_DEFAULT_REGION:    "us-east-1"
    AWS_BACKEND_BUCKET:    "tf-bucket-shotorouu"
    AWS_BACKEND_TABLE:     "tf-state-shotorouu"

stages:
    - validate
    - plan
    - apply
    - destroy

default:
  before_script:
    - cd ./config
    - terraform init -backend-config="bucket=${AWS_BACKEND_BUCKET}" -backend-config="dynamodb_table=${AWS_BACKEND_TABLE}"

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  dependencies:
    - validate
  script:
    - terraform plan -out="planfile"
  artifacts:
    paths:
      - "config/planfile"

apply:
  stage: apply
  dependencies:
    - plan
  script:
    - terraform apply -input=false "planfile"
  when: manual

destroy:
  stage: destroy
  script:
    - terraform destroy -auto-approve
  when: manual
